services:
  carlov_panel:
    restart: unless-stopped
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - '802:8000'
    volumes:
      - ./:/app
    #      - ./app:/app
    command: 'php artisan serve --host=0.0.0.0'
    stdin_open: true
    tty: true
    environment:
      - HOME=/tmp
    depends_on:
      - carlov_db
    networks:
      - carlov

  carlov_db:
    restart: unless-stopped
    image: mysql:8
    container_name: carlov_db
    ports:
      - "0.0.0.0:3309:3306"
    environment:
      MYSQL_DATABASE: carlov
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
    volumes:
      - ./storage/dbdata:/var/lib/mysql
    networks:
      - carlov
networks:
  carlov:
