services:
  cv-nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ../public:/var/www/html/public:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - cv-app
    restart: unless-stopped

  cv-app:
    build: .
    volumes:
      - ../:/var/www/html
    environment:
      DB_HOST: cv-mysql
      DB_DATABASE: carlov
      DB_USERNAME: root
      DB_PASSWORD: password123
      REDIS_HOST: cv-carlov_redis
    # Permette al container di accedere alla rete dell'host per stampanti POS
    # Opzione 1: Usa network_mode host (decommenta SOLO se hai problemi di connessione)
    # network_mode: "host"
    # Opzione 2: Usa extra_hosts per mappare hostname (opzionale)
#    extra_hosts:
#       - "stampante-cucina:192.168.8.200"
    depends_on:
      - cv-mysql
      - cv-carlov_redis
    restart: unless-stopped

  cv-mysql:
    image: mysql:8.0
    ports:
        - "3309:3306"
    environment:
      MYSQL_DATABASE: carlov
      MYSQL_ROOT_PASSWORD: password123
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped

  cv-carlov_redis:
    image: redis:7-alpine
    restart: unless-stopped

  cv-phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8082:80"
    environment:
      PMA_HOST: cv-mysql
      PMA_USER: root
      PMA_PASSWORD: password123
    depends_on:
      - cv-mysql
    restart: unless-stopped

volumes:
  mysql_data:
